admin.property.index:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index

admin.property.new:
  path: /admin/property/create
  controller: App\Controller\Admin\AdminPropertyController::new

admin.property.edit:
  path: /admin/property/{id}
  controller: App\Controller\Admin\AdminPropertyController::edit
  methods: GET|POST

admin.property.delete:
  path: /admin/property/{id}
  controller: App\Controller\Admin\AdminPropertyController::delete
  methods: ['DELETE']

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
