home:
    path: /
    controller: App\Controller\HomeController::index

property.index:
    path: /biens
    controller: App\Controller\PropertyController::index

property.show:
    path: /biens/{slug}-{id}
    controller: App\Controller\PropertyController::show
    requirements: {'slug': '[a-z0-9\-]*'}


app_login:
    path: /login
    controller: App\Controller\SecurityController::login


app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
