<?php

namespace App\Form;

use App\Entity\PropertiSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertiSearchType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('minSurface',IntegerType::class,[
                'required' => false,
                'label' => false,
                'attr' => [
                    'placeholder' => 'Surface minimale'
                ]
            ])
            ->add('maxPrice',IntegerType::class,[
                'required' => false,
                'label' => false,
                'attr' => [
                    'placeholder' => 'Budget maximal'
                ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PropertiSearch::class,
            'method'=> 'get',  //Methode get, car on fait juste une recherche
            'csrf_protection' => false   //Token désactivé car pas besoin de token pour faire une recherche
        ]);
    }

    /**
     * Permet de modifier le stub (parametres de l'url) généré automatiquement
     * Affiche les noms champs
     * @return string
     */
    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}
